import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import PageLayout from '@/components/PageLayout'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home({articles}) {

  return (

    <PageLayout title = "News App - Home" >

    <div className={styles.container}>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {articles.length === 0 && <p>No hay artículos</p>}
      {articles.length > 0 && articles.map((article, index) => (
        <article key={index} >
          <img src={article.urlToImage} alt="" />
          <h2>{article.title}</h2>
          <p>{article.description}</p>
        </article>
      ))}
      
    </div>

    </PageLayout>
  )
}

export async function getServerSideProps() {
  const response = await fetch('https://newsapi.org/v2/everything?q=tesla&from=2022-12-19&sortBy=publishedAt&apiKey=92b29c7264864016892c34a9fbebb01b')
  const {articles} = await response.json()

  return {
    props: {
      articles
    }
  }
 
}